export const LOCATION_CATEGORIES = [
  "Abattoir",
  "Abri De Jardin",
  "Aéroport",
  "Ambassade",
  "Antenne Relais",
  "Appartement",
  "Ascenseur",
  "Atelier",
  "Autoroute",
  "Avion",
  "Banque",
  "Bar",
  "Barrage",
  "Base Militaire",
  "Bateau",
  "Bibliothèque",
  "Boîte De Nuit",
  "Boutique",
  "Bureau",
  "Cabinet Dentaire",
  "Cabinet Médical",
  "Café",
  "Camping",
  "Carrière",
  "Cascade",
  "Casino",
  "Cave",
  "Centrale Électrique",
  "Champ",
  "Chantier",
  "Château",
  "Château D'eau",
  "Cimetière",
  "Cinéma",
  "Cirque",
  "Commissariat",
  "Cuisine Professionnelle",
  "Décharge",
  "Désert",
  "École",
  "Écurie",
  "Église",
  "Entrepôt",
  "Espace Futuriste",
  "Escalier",
  "Ferme",
  "Forêt",
  "Galerie D'art",
  "Garage",
  "Garage Automobile",
  "Gare",
  "Golf",
  "Grange",
  "Grenier",
  "Grotte",
  "Gymnase",
  "Hangar",
  "Hélicoptère",
  "Hôpital",
  "Hôtel",
  "Installation Sportive",
  "Institut De Beauté",
  "Jardin",
  "Laboratoire",
  "Lac",
  "Laverie Automatique",
  "Lavoir",
  "Lieu Historique",
  "Loft",
  "Mairie",
  "Maison",
  "Manoir",
  "Marché Couvert",
  "Métro",
  "Montagne",
  "Moulin",
  "Musée",
  "Observatoire",
  "Parc",
  "Parc D'attraction",
  "Parking",
  "Pépinière",
  "Périmètre Industriel",
  "Pharmacie",
  "Phare",
  "Piscine",
  "Place",
  "Plage",
  "Plateforme Pétrolière",
  "Pont",
  "Port",
  "Potager",
  "Prison",
  "Restaurant",
  "Rivière",
  "Route De Campagne",
  "Rue",
  "Ruines",
  "Salle De Spectacle",
  "Salon De Coiffure",
  "Sauna / Spa",
  "Serre",
  "Stade",
  "Station-Service",
  "Studio",
  "Supermarché",
  "Terrain De Tennis",
  "Théâtre",
  "Toit-Terrasse (Rooftop)",
  "Train",
  "Tribunal",
  "Tunnel",
  "Usine",
  "Verger",
  "Vignoble",
  "Village",
  "Zoo"
];
