workflows:
  android-production:
    name: Android Production Build
    max_build_duration: 60
    instance_type: mac_mini_m4
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    environment:
      node: 20
      java: 17
      groups:
        - eas_credentials
        - Android_keystores
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
       
    scripts:
      - name: Recreate config files
        script: |
          if [ -z "$GOOGLE_SERVICES_ANDROID" ]; then
            echo "ERREUR : La variable GOOGLE_SERVICES_ANDROID est vide dans Codemagic !"
            exit 1
          fi
          node -e "const fs = require('fs'); if (process.env.GOOGLE_SERVICES_IOS) { fs.writeFileSync('./GoogleService-Info.plist', Buffer.from(process.env.GOOGLE_SERVICES_IOS, 'base64')); console.log('GoogleService-Info.plist created'); } if (process.env.GOOGLE_SERVICES_ANDROID) { fs.writeFileSync('./google-services.json', Buffer.from(process.env.GOOGLE_SERVICES_ANDROID, 'base64')); console.log('google-services.json created'); }"
          ls -l google-services.json || echo "Le fichier n'a pas été créé !"
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android
      - name: Build Android Release
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - paulpousset@gmail.com

  ios-production:
    name: iOS Production Build (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m4
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - $HOME/Library/Caches/CocoaPods
    integrations:
      app_store_connect: "CodeMagic"
    environment:
      node: 20
      groups:
        - eas_credentials
      vars:
        XCODE_WORKSPACE: "ios/Tita.xcworkspace"
        XCODE_SCHEME: "Tita"
        BUNDLE_ID: "com.titasorganization.tita"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'ignore-master' # Désactivé au profit de GitHub Actions
    scripts:
      - name: Recreate config files
        script: |
          node -e "const fs = require('fs'); if (process.env.GOOGLE_SERVICES_IOS) { fs.writeFileSync('./GoogleService-Info.plist', Buffer.from(process.env.GOOGLE_SERVICES_IOS, 'base64')); console.log('GoogleService-Info.plist created'); } if (process.env.GOOGLE_SERVICES_ANDROID) { fs.writeFileSync('./google-services.json', Buffer.from(process.env.GOOGLE_SERVICES_ANDROID, 'base64')); console.log('google-services.json created'); }"
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform ios --clean
      - name: Set up code signing
        script: |
          keychain initialize
          # Fetch and install the signing files
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --install --create
          # Debug: List downloaded profiles
          ls ~/Library/MobileDevice/Provisioning\ Profiles
          # Update entitlements safely
          ENTITLEMENTS_FILE="ios/Tita/Tita.entitlements"
          if [ -f "$ENTITLEMENTS_FILE" ]; then
            /usr/libexec/PlistBuddy -c "Add :aps-environment string production" "$ENTITLEMENTS_FILE" || /usr/libexec/PlistBuddy -c "Set :aps-environment production" "$ENTITLEMENTS_FILE"
            /usr/libexec/PlistBuddy -c "Add :com.apple.developer.applesignin array" "$ENTITLEMENTS_FILE" || true
            /usr/libexec/PlistBuddy -c "Add :com.apple.developer.applesignin:0 string Default" "$ENTITLEMENTS_FILE" || true
            echo "Entitlements updated in $ENTITLEMENTS_FILE"
            cat "$ENTITLEMENTS_FILE"
          fi
          # Match the profiles to the project
          # Explicitly set the project file and turn off automatic signing
          xcode-project use-profiles --project ios/Tita.xcodeproj --bundle-identifier "$BUNDLE_ID"
      - name: Build iOS IPA
        script: |
          # Use xcode-project build-ipa with explicit parameters
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --bundle-identifier "$BUNDLE_ID" \
            --archive-flags "CODE_SIGN_STYLE=Manual"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - paulpousset@gmail.com
