workflows:
  android-production:
    name: Android Production Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20
      java: 17
      groups:
        - eas_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
    scripts:
      - name: Recreate config files
        script: |
          if [ -z "$GOOGLE_SERVICES_ANDROID" ]; then
            echo "ERREUR : La variable GOOGLE_SERVICES_ANDROID est vide dans Codemagic !"
            exit 1
          fi
          node -e "const fs = require('fs'); if (process.env.GOOGLE_SERVICES_IOS) { fs.writeFileSync('./GoogleService-Info.plist', Buffer.from(process.env.GOOGLE_SERVICES_IOS, 'base64')); console.log('GoogleService-Info.plist created'); } if (process.env.GOOGLE_SERVICES_ANDROID) { fs.writeFileSync('./google-services.json', Buffer.from(process.env.GOOGLE_SERVICES_ANDROID, 'base64')); console.log('google-services.json created'); }"
          ls -l google-services.json || echo "Le fichier n'a pas été créé !"
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android
      - name: Build Android Release
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - paulpousset@gmail.com

  ios-production:
    name: iOS Production Build (TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "CodeMagic" # Remplace par le nom exact de ton intégration dans Codemagic
    environment:
      node: 20
      groups:
        - eas_credentials
      vars:
        XCODE_WORKSPACE: "ios/Tita.xcworkspace"
        XCODE_SCHEME: "Tita"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
    scripts:
      - name: Recreate config files
        script: |
          node -e "const fs = require('fs'); if (process.env.GOOGLE_SERVICES_IOS) { fs.writeFileSync('./GoogleService-Info.plist', Buffer.from(process.env.GOOGLE_SERVICES_IOS, 'base64')); console.log('GoogleService-Info.plist created'); } if (process.env.GOOGLE_SERVICES_ANDROID) { fs.writeFileSync('./google-services.json', Buffer.from(process.env.GOOGLE_SERVICES_ANDROID, 'base64')); console.log('google-services.json created'); }"
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform ios
      - name: Set up code signing
        script: |
          keychain initialize
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - paulpousset@gmail.com
