workflows:
  android-development:
    name: Android Development Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      node: 20
      java: 17
      groups:
        - eas_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
    scripts:
      - name: Recreate config files
        script: |
          if [ -z "$GOOGLE_SERVICES_ANDROID" ]; then
            echo "ERREUR : La variable GOOGLE_SERVICES_ANDROID est vide dans Codemagic !"
            exit 1
          fi
          node -e "const fs = require('fs'); if (process.env.GOOGLE_SERVICES_IOS) { fs.writeFileSync('./GoogleService-Info.plist', Buffer.from(process.env.GOOGLE_SERVICES_IOS, 'base64')); console.log('GoogleService-Info.plist created'); } if (process.env.GOOGLE_SERVICES_ANDROID) { fs.writeFileSync('./google-services.json', Buffer.from(process.env.GOOGLE_SERVICES_ANDROID, 'base64')); console.log('google-services.json created'); }"
          ls -l google-services.json || echo "Le fichier n'a pas été créé !"
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild (if needed)
        script: |
          npx expo prebuild --platform android
      - name: Build Android App
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - paulpousset@gmail.com
  
  android-production:
    name: Android Production Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20
      java: 17
      groups:
        - eas_credentials
    scripts:
      - name: Recreate config files
        script: |
          if [ -z "$GOOGLE_SERVICES_ANDROID" ]; then
            echo "ERREUR : La variable GOOGLE_SERVICES_ANDROID est vide dans Codemagic !"
            exit 1
          fi
          node -e "const fs = require('fs'); if (process.env.GOOGLE_SERVICES_IOS) { fs.writeFileSync('./GoogleService-Info.plist', Buffer.from(process.env.GOOGLE_SERVICES_IOS, 'base64')); console.log('GoogleService-Info.plist created'); } if (process.env.GOOGLE_SERVICES_ANDROID) { fs.writeFileSync('./google-services.json', Buffer.from(process.env.GOOGLE_SERVICES_ANDROID, 'base64')); console.log('google-services.json created'); }"
          ls -l google-services.json || echo "Le fichier n'a pas été créé !"
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android
      - name: Build Android Release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      - android/app/build/outputs/bundle/**/*.aab
