export const JOB_TITLES = {
  realisateur: [
    "Réalisateur",
    "1er Ass. Réal.",
    "2ème Ass. Réal.",
    "Scripte",
    "Storyboarder",
  ],
  acteur: [
    "Rôle Principal",
    "Rôle Secondaire",
    "Silhouette",
    "Figurant",
    "Doublure",
    "Modèle",
  ],
  production: [
    "Directeur de Prod.",
    "Chargé de Prod.",
    "Régisseur Général",
    "Régisseur Adj.",
    "Runner/Chauffeur",
    "Cantine",
  ],
  image: [
    "Chef Opérateur",
    "Cadreur",
    "1er Ass. Caméra",
    "2ème Ass. Caméra",
    "Steadicamer",
    "Chef Élec. (Gaffer)",
    "Électricien",
    "Chef Machino",
    "Machiniste",
  ],
  son: ["Ingénieur du Son", "Perchman", "Mixeur Plateau"],
  hmc: [
    "Chef Costumier",
    "Habilleur",
    "Chef Maquilleur",
    "Coiffeur",
    "Maquilleur FX",
  ],
  deco: [
    "Chef Décorateur",
    "Accessoiriste",
    "Rippeur",
    "Constructeur",
    "Peintre",
  ],
  post_prod: [
    "Monteur Image",
    "Monteur Son",
    "Étalonneur",
    "VFX Artist",
    "Compositeur",
    "Mixeur",
  ],
  technicien: ["Autre Technicien"], // Categorie fourre-tout au cas où
};
